---
title: "Manual filtering"
output: html_notebook
---

```{r setup, include = FALSE}
# install and load required packages
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("wesanderson")) {install.packages("wesanderson"); require("wesanderson")}

# ggplots
theme_set(theme_classic())
theme_update(text = element_text(size = 20, family = "Helvetica Neue LT Std 57 Condensed"), legend.position = "bottom")

# read csv
df_all <- read.csv("./filtered/data_all.csv", header = T, sep = ",", dec = ".")
df_onset <- df_all %>% dplyr::filter(Key_OnOff == 1)
df_removed_onset <- read.csv("./filtered/data_removed_onset.csv", header = T, sep = ",", dec = ".") # removed trials by the first filtering

df_ideal <- read.table("./ideal.txt")
colnames(df_ideal) <- "Pitch"
df_ideal$RowNr <- c(1:nrow(df_ideal))
df_ideal <- df_ideal[c(2, 1)]

# create data frame to save data without errors
df_container <- data.frame()
```

```{r manual_filtering, echo = FALSE}
manual_filtering <- function(current_onset, ideal){
  counter = 0
  if (nrow(current_onset) > length(ideal$Pitch) & nrow(current_onset) < length(ideal$Pitch)*1.05){ # if there are more notes than ideal
    df_error$errorType[i] <<- "More"
    for (note in 1:length(ideal$Pitch)){
      # detect onset error
      if (current_onset[note,]$Pitch != ideal$Pitch[note]){
        while (counter == 0) {
          df_error$errorFirst[i] <<- note
          print(sprintf("Onset-Pitch error - RowNr: %i", note))
          counter = counter + 1
        }
      }
    }
  } else if (nrow(current_onset) > length(ideal$Pitch)*0.95 & nrow(current_onset) < length(ideal$Pitch) & nrow(current_onset)){ # if there are less note than ideal
    df_error$errorType[i] <<- "Less"
    for (note in 1:nrow(current_onset)){
      # detect onset error
      if (current_onset[note,]$Pitch != ideal$Pitch[note]){
        while (counter == 0) {
          df_error$errorFirst[i] <<- note
          print(sprintf("Onset-Pitch error - RowNr: %i", note))
          counter = counter + 1
        }
      }
    }
  } else if (nrow(current_onset) == length(ideal$Pitch)){ # there are equal notes to ideal
    for (note in 1:nrow(current_onset)){
      df_error$errorType[i] <<- "Equal"
      # detect onset error
      if (current_onset[note,]$Pitch != ideal$Pitch[note]){
        while (counter == 0) {
          df_error$errorFirst[i] <<- note
          print(sprintf("Onset-Pitch error - RowNr: %i", note))
          counter = counter + 1
        }
      }
    } 
  } else if (nrow(current_onset) >= length(ideal$Pitch)*1.05){ # error more than 5%
    df_error$errorType[i] <<- "Exclude"
    df_error$errorFirst[i] <<- "Exclude the trial (more than 5%)"
  } else if (nrow(current_onset) <= length(ideal$Pitch)*0.95){ # error more than 5%
    df_error$errorType[i] <<- "Exclude"
    df_error$errorFirst[i] <<- "Exclude the trial (less than 5%)"
  } else { # other problems
    df_error$errorType[i] <<- "Other"
    df_error$errorFirst[i] <<- "Check individually"
  }
}
```

# Each participant
# First run
```{r first_error, echo = FALSE}
df_error <- data.frame(df_removed_onset)
for (i in 1:nrow(df_error)){
  print(i)
  current <- df_onset %>% dplyr::filter(SubNr == df_removed_onset[i,1], BlockNr == df_removed_onset[i,2], TrialNr == df_removed_onset[i,3])
  current$RowNr = c(1:nrow(current))
  manual_filtering(current, df_ideal)
}
df_error
```

```{r plot, echo = FALSE}
for (i in 1:nrow(df_removed_onset)){
  print(i)
  current <- df_onset %>% dplyr::filter(SubNr == df_removed_onset[i,1], BlockNr == df_removed_onset[i,2], TrialNr == df_removed_onset[i,3])
  current$RowNr = c(1:nrow(current))
  
  plot <- ggplot() +
    geom_line(data = current, aes(x = RowNr, y = Pitch), colour = "#F8766D") + 
    geom_line(data = df_ideal, aes(x = RowNr, y = Pitch), colour = "#00BFC4") +
    geom_point(data = current, aes(x = RowNr, y = Pitch), colour = "#F8766D") +
    geom_point(data = df_ideal, aes(x = RowNr, y = Pitch), colour = "#00BFC4") +
    scale_x_continuous("RowNr", current$RowNr) +
    labs(title = sprintf("SubNr: %i, BlockNr: %i, TrialNr: %i", df_removed_onset[i,1], df_removed_onset[i,2], df_removed_onset[i,3]))
  
  print(plot)
}
```

```{r manual_filtering_2, echo = FALSE}
manual_filtering_2 <- function(current_onset, ideal){
  counter = 0
  if (nrow(current_onset) > length(ideal$Pitch) & nrow(current_onset) < length(ideal$Pitch)*1.05){ # if there are more notes than ideal
    df_error$errorType2[i] <<- "More"
    for (note in 1:length(ideal$Pitch)){
      # detect onset error
      if (current_onset[note,]$Pitch != ideal$Pitch[note]){
        while (counter == 0) {
          df_error$errorSecond[i] <<- note
          print(sprintf("Onset-Pitch error - RowNr: %i", note))
          current_onset <- current_onset[-note,]
          counter = counter + 1
        }
      }
    }
  } else if (nrow(current_onset) > length(ideal$Pitch)*0.95 & nrow(current_onset) < length(ideal$Pitch) & nrow(current_onset)){ # if there are less note than ideal
    df_error$errorType2[i] <<- "Less"
    for (note in 1:nrow(current_onset)){
      # detect onset error
      if (current_onset[note,]$Pitch != ideal$Pitch[note]){
        while (counter == 0) {
          df_error$errorSecond[i] <<- note
          print(sprintf("Onset-Pitch error - RowNr: %i", note))
          current_onset[note,] <- NA
          counter = counter + 1
        }
      }
    }
  } else if (nrow(current_onset) == length(ideal$Pitch)){ # there are equal notes to ideal
    for (note in 1:nrow(current_onset)){
      df_error$errorType2[i] <<- "Equal"
      # detect onset error
      if (current_onset[note,]$Pitch != ideal$Pitch[note]){
        while (counter == 0) {
          df_error$errorSecond[i] <<- note
          print(sprintf("Onset-Pitch error - RowNr: %i", note))
          counter = counter + 1
        }
      }
    } 
  }
}
```

```{r second-run, echo = FALSE}
for (i in 1:nrow(df_error)){
  current <- df_onset %>% dplyr::filter(SubNr == df_error[i,1], BlockNr == df_error[i,2], TrialNr == df_error[i,3])
  current$RowNr = c(1:nrow(current))
  if (df_error$errorType[i] == "More"){
    print(i)
    current <- current[-as.integer(df_error$errorFirst[i]),]
    manual_filtering_2(current, df_ideal)
  } else if (df_error$errorType[i] == "Less"){
    print(i)
    current[as.integer(df_error$errorFirst[i]),] <- NA
    manual_filtering_2(current[-as.integer(df_error$errorFirst[i]),], df_ideal[-as.integer(df_error$errorFirst[i]),])
  }
}
```

# Remove the first error
```{r remove_twomasures, echo = FALSE}
for (i in c(1:length(df_error$errorType))){
  current <- df_onset %>% dplyr::filter(SubNr == df_removed_onset[i,1], BlockNr == df_removed_onset[i,2], TrialNr == df_removed_onset[i,3])
  current$RowNr = c(1:nrow(current))
  if (df_error$errorType[i] == "More"){
    if (df_error$errorFirst[i] <= 8){
      current <- current %>% dplyr::filter(RowNr > 17)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 16))
    } else if (df_error$errorFirst[i] > 8 & df_error$errorFirst[i] <= 16){
      current <- current %>% dplyr::filter(RowNr > 25)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 24))
    } else if (df_error$errorFirst[i] > 16 & df_error$errorFirst[i] <= 24){
      current <- current %>% dplyr::filter(RowNr > 29)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 28))
    } else if (df_error$errorFirst[i] > 24 & df_error$errorFirst[i] <= 28){
      current <- current %>% dplyr::filter(RowNr > 34)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 33))
    } else if (df_error$errorFirst[i] > 28 & df_error$errorFirst[i] <= 33){
      current <- current %>% dplyr::filter(RowNr > 40)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 39))
    } else if (df_error$errorFirst[i] > 33 & df_error$errorFirst[i] <= 39){
      current <- current %>% dplyr::filter(RowNr > 48)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 47))
    } else if (df_error$errorFirst[i] > 39 & df_error$errorFirst[i] <= 47){
      current <- current %>% dplyr::filter(RowNr > 53)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 52))
    } else if (df_error$errorFirst[i] > 47 & df_error$errorFirst[i] <= 52){
      current <- current %>% dplyr::filter(RowNr > 58)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 57))
    } else if (df_error$errorFirst[i] > 52){
    }
  } else if (df_error$errorType[i] == "Less"){
    if (df_error$errorFirst[i] <= 8){
      current <- current %>% dplyr::filter(RowNr > 15)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 16))
    } else if (df_error$errorFirst[i] > 8 & df_error$errorFirst[i] <= 16){
      current <- current %>% dplyr::filter(RowNr > 24)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 24))
    } else if (df_error$errorFirst[i] > 16 & df_error$errorFirst[i] <= 24){
      current <- current %>% dplyr::filter(RowNr > 27)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 28))
    } else if (df_error$errorFirst[i] > 24 & df_error$errorFirst[i] <= 28){
      current <- current %>% dplyr::filter(RowNr > 32)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 33))
    } else if (df_error$errorFirst[i] > 28 & df_error$errorFirst[i] <= 33){
      current <- current %>% dplyr::filter(RowNr > 48)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 39))
    } else if (df_error$errorFirst[i] > 33 & df_error$errorFirst[i] <= 39){
      current <- current %>% dplyr::filter(RowNr > 46)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 47))
    } else if (df_error$errorFirst[i] > 39 & df_error$errorFirst[i] <= 47){
      current <- current %>% dplyr::filter(RowNr > 52)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 52))
    } else if (df_error$errorFirst[i] > 47 & df_error$errorFirst[i] <= 52){
      current <- current %>% dplyr::filter(RowNr > 56)
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 57))
    } else if (df_error$errorFirst[i] > 52){
    }
  } 
}
```

# Second error
```{r manual_filter_2, include = FALSE}
df_error$errorSecond <- NA
manual_filtering_2 <- function(current_onset, ideal){
  counter = 0
    for (note in 1:length(ideal$Pitch)){
      # detect onset error
      if (current_onset[note,]$Pitch != ideal$Pitch[note]){
        while (counter == 0) {
          df_error$errorSecond[i] <<- note
          print(sprintf("Onset-Pitch error - RowNr: %i", note))
          counter = counter + 1
       }
    }
  }
}
```

```{r second_error, echo = FALSE}
for (i in c(1:length(df_error$errorNote))){
  current <- df_onset %>% dplyr::filter(SubNr == df_removed_onset[i,1], BlockNr == df_removed_onset[i,2], TrialNr == df_removed_onset[i,3])
  if (df_error$errorType == "More"){
    if (df_error$errorNote[i] <= 8){
      current_second <- current %>% dplyr::filter(RowNr > df_error$errorFirst[i])
      manual_filtering_2(current, subset(df_ideal, df_ideal$RowNr > 17))
    } else if (df_error$errorFirst[i] <= 16){
      print(a)
    } else if (df_error$errorFirst[i] <= 24){
      print(a)
    } else if (df_error$errorFirst[i] <= 33){
      print(a)
    } else if (df_error$errorFirst[i] <= 39){
      print(a)
    } else if (df_error$errorFirst[i] <= 52){
      print(a)
    } else if (df_error$errorFirst[i] > 53){
    }
  }
}


# after two measures
-
current_6 <- current_6 %>% dplyr::filter(RowNr > 56)
manual_filtering(current_6, subset(df_ideal, df_ideal$RowNr > 57))

+
current_6 <- current_6 %>% dplyr::filter(RowNr > 56)
manual_filtering(current_6, subset(df_ideal, df_ideal$RowNr > 55))

# rescue after RowNr 56
container_6 <- rbind(container_6, current_6)
container_6
```

